name: Fetch Repository Stats

on:
  schedule:
    # Run every day at 23:30 UTC
    - cron: "30 23 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch and Compile GitHub Traffic Data
        uses: jgehrcke/github-repo-stats@v1.4.2
        with:
          repository: ${{ github.repository }}
          ghtoken: ${{ secrets.GHRS_GITHUB_API_TOKEN }}
